### PR TITLE
Patch navigator.sendBeacon to send data as blob

### LINKED ISSUE #74: navigator.sendBeacon support
`navigator.sendBeacon` accepts `FormData` but doesn't work with this polyfill.

It can be patched similar to how `fetch` is, as it also accepts `Blob` (confirmed working on Edge).

### PR DESCRIPTION
**Pull request by glebm**
Fixes #74 

Note: It may be possible to use `_asNative` instead but would need testing.

### CODE REVIEW

**Comment by jimmywarting** [comment]
Guess it faster/smarter to construct a new native FormData then creating a new large blob...

_asNative works for IE10+ 
_blob works for much older IE version if they include a [blob](https://github.com/eligrey/Blob.js/blob/master/Blob.js) polyfill

But navigator.sendBeacon is not avalible in IE at all

File: FormData.js [hunk 1]
```diff
@@ -386,5 +387,15 @@ if (typeof Blob === 'function' && (typeof FormData === 'undefined' || !FormData.
     }
   }
 
+  // Patch navigator.sendBeacon to use the underlying Blob
+  if (_sendBeacon) {
+    global.navigator.sendBeacon = function (url, data) {
+      if (data instanceof FormDataPolyfill) {
+        data = data['_blob']()
+      }
+      return _sendBeacon(url, data)
```
Comment (jimmywarting) [inline FormData.js]: figured out i can't accept this PR...

you need to use `call` when saving sendBeacon to some variable

```suggestion
      return _sendBeacon.call(navigator, url, data)
```
Otherwise you get `Uncaught TypeError: Illegal invocation`

Comment (glebm) [reply FormData.js]: Thanks, good catch! Fixed!
